name: Documentation e2e
on:
  pull_request:
    branches: [main]

jobs:
  docs-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Change directory to /docs
        run: cd docs

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run: |
          cd docs
          npm install -g pnpm
          pnpm install

      - name: ğŸŒ Install Playwright Browsers
        run: |
          cd docs
          pnpm exec playwright install --with-deps

      - name: ğŸ”„ï¸ Start Docusaurus server
        run: |
          cd docs
          npm run serve &
        env:
          NODE_ENV: development

      - name: ğŸ“‹ Run Playwright tests
        run: |
          cd docs
          pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: docs/playwright-report/
          retention-days: 30
